---
title: My Publications
---
- [Abiodun Ojo, Bolatito Aiyenigba, Johnbull, S., Adamu Onu, Olabanji Ipadeola, Salihu, M., Kolawole Maxwell, Baba, E., & Abba Umar. (2014). Malaria Diagnostic Service Availability‐Mapping of Private Sector Service Delivery Outlets in 7 PMI/MAPS Supported States, Nigeria. American Journal of Tropical Medicine and Hygiene, 91(5 suppl), 79.](https://doi.org/10.13140/rg.2.1.1463.2722)
- [Agbaji, O. O., Onu, A., Agaba, P. E., Muazu, M. A., Falang, K. D., & Idoko, J. A. (2011). Predictors of impaired renal function among HIV infected patients commencing highly active antiretroviral therapy in Jos, Nigeria. Nigerian Medical Journal: Journal of the Nigeria Medical Association, 52(3), 182–185. https://doi.org/10.4103/0300-1652.86133](https://doi.org/10.4103/0300-1652.86133)
- [Akanbi, M. O., Achenbach, C. J., Feinglass, J., Taiwo, B., Onu, A., Pho, M. T., Agbaji, O., Kanki, P., & Murphy, R. L. (2013). Tuberculosis after one year of combination antiretroviral therapy in Nigeria: A retrospective cohort study. AIDS Research and Human Retroviruses, 29(6), 931–937. https://doi.org/10.1089/aid.2012.0231](https://doi.org/10.1089/aid.2012.0231)
- Dawam, J. A., Madaki, J. K. A., Gambazai, A. A., Okpe, E. S., Lar-ndam, N., Onu, A., & Gyang, M. (2016). Monthly sulphadoxine-pyrimethamine combination versus daily proguanil for malaria chemoprophylaxis in sickle cell disease: A randomized controlled study at the Jos University Teaching Hospital. Nigerian Journal of Medicine: Journal of the National Association of Resident Doctors of Nigeria, 25(2), 119–127.
- Ogiator, M., Onu, A., Agbaji, O., Agaba, E., Ojobi, J., & Ogiator. (2015). The prevalence of and risk factors for chronic kidney disease in spouses of patients with advanced chronic kidney disease. Highland Medical Research Journal, 15(1), 27–30.
- [Onu, A. (2021). Effect of Insecticide-Treated Nets on Anemia in Nigerian Children. Walden Dissertations and Doctoral Studies. https://doi.org/10.13140/RG.2.2.21698.09920](https://doi.org/10.13140/RG.2.2.21698.09920)
- Oreh, A. C., Onu, A., & Moses, A. L. (2021). Prevalence and Determinants of Helicobacter Pylori Infection among Adult Dyspeptic Patients in Abuja, Nigeria. West African Journal of Medicine, 38(8), 775–784.
- Oreh, A., Onu, A., & Moses, A. (2021a, November 25). Implications of dietary and hygiene factors and Helicobacter pylori infection in Nigeria – results from an urban hospital-based study. 23rd World Conference of Family Doctors 2021.
- Oreh, A., Onu, A., & Moses, A. (2021b, November 25). Use of Patient Dyspepsia Scores from the Short-Form Leeds Dyspepsia Questionnaire in Early Diagnosis and Treatment of Helicobacter pylori infection. 23rd World Conference of Family Doctors 2021.
